### ISSUE TITLE
Problem with database connection

### ISSUE THREAD

**Issue by ttngr05** [Ender-Cube/StomKor#2]
tomas@neway:~/mcserver$ java -jar StomKor-1.5.0.jar
12:12:23 [INFO]: Starting Minestom server.
12:12:24 [INFO]: Minestom server started successfully.
12:12:24 [INFO]: Starting server on port 25565 with ONLINE encryption
12:12:24 [INFO]: HikariPool-1 - Starting...
12:12:24 [INFO]: HikariPool-1 - Added connection org.mariadb.jdbc.Connection@4e6f2bb5
12:12:24 [INFO]: HikariPool-1 - Start completed.
12:12:24 [WARN]: Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''playerTimes' (
    player text NOT NULL,
    course text NOT NULL,
    time ...' at line 1
12:12:24 [ERROR]: Failed to create table
Exception in thread "main" java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: (conn=217) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''playerTimes' (
    player text NOT NULL,
    course text NOT NULL,
    time ...' at line 1
        at net.endercube.EndercubeCommon.utils.SQLWrapper.createTable(SQLWrapper.java:258)
        at net.endercube.EndercubeCommon.utils.SQLWrapper.<init>(SQLWrapper.java:34)
        at net.endercube.EndercubeCommon.EndercubeGame.initSQL(EndercubeGame.java:201)
        at net.endercube.EndercubeCommon.EndercubeGame.build(EndercubeGame.java:147)
        at me.zax71.stomKor.Main.main(Main.java:70)
Caused by: java.sql.SQLSyntaxErrorException: (conn=217) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''playerTimes' (
    player text NOT NULL,
    course text NOT NULL,
    time ...' at line 1
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:872)
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:811)
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:730)
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:654)
        at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95)
        at org.mariadb.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:288)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at net.endercube.EndercubeCommon.utils.SQLWrapper.createTable(SQLWrapper.java:254)
        ... 4 more

**Comment by zax71** [comment]
Oh yeah, that's known. I'm abandoning this for now and switching to [Ender-Cube/Endercube](https://github.com/Ender-Cube/Endercube). I'll archive this repo when the new version is in prod
